name: Build and deploy ASP.Net Core 8 App to Azure Web App - empcurdwebapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup .NET 8
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # 3️⃣ Restore dependencies
      - name: Restore dependencies
        run: dotnet restore EmpCurdAzureRepo.sln

      # 4️⃣ Build solution
      - name: Build solution
        run: dotnet build EmpCurdAzureRepo.sln -c Release --no-restore

      # 5️⃣ Publish project
      - name: Publish project
        run: dotnet publish EmpCurdAzureRepo.csproj -c Release -o ./publish

      # 6️⃣ Login to Azure using Service Principal JSON
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 7️⃣ Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'empcurdwebapp'  # Your Azure Web App name
          package: ./publish
